### ISSUE TITLE
Fitting using vector of start values 

### ISSUE THREAD

**Issue by schatterjee30** [aursiber/fitdistrplus#10]
Hi,
My current analysis involves a regression using a non-standard distribution Poisson-inverse Gaussian.
The distribution function is in the package actuar (dpoisinvgauss(mean, shape).
My model is... 
Mean=exp(X*beta) given y=observed data, X=design 
So, my parameters are beta=(beta0,beta1) and shape.
Let's say the initial values of beta=c(1,1).
n=50, n1=25, n2= 25, where n = length(y).
So, X = data.frame(Intercept=rep(0,n), Treatment=rep(c(0,1), c(n1,n2))
Then initial values for mean,
mu= X*beta which is a vector (nx1).
I am not regressing the shape parameters hence (let's say) initial value of shape =1.
Based on the tutorial...
start = list(mean=mu, shape=shape). Note mean is a vector while shape is a scalar here.
Then for fitting I am using..
fit= fitdist(y,'poisinvgauss', start=start, 'L-BFGS-B, lower=c(0,0),discrete=T).
I am getting this error..
"Error in checkparamlist(arg_startfix$start.arg, arg_startfix$fix.arg,  : 
  'start' must specify names which are arguments to 'distr'."
Questions:
Is it possible to accomplish what I am trying? 
If so, can you please let me know how I can do that?
Sorry, for the long description. Thanks in advance!

**Comment by dutangc** [comment]
Can you put a (small) reproducible example? Otherwise it is difficult to say anything.
