### ISSUE TITLE
gofstat does not use the log of the density function

### ISSUE THREAD

**Issue by naveranoc** [aursiber/fitdistrplus#13]
Hello,

Thanks for this impressive package!.

I think there is a problem when calculating the log likelihood within the package, since it seems to be calculating the logarithm of the density and ignoring if the density function accepts the log as part of the function, generating statistics that are infinite (Which using the function log does not pass).

Here is the part of code with the issue.

if (is.null(weights)) {
    loglik <- function(par, fix.arg, obs, ddistnam) sum(log(do.call(ddistnam, 
                                                                    c(list(obs), as.list(par), as.list(fix.arg),log = T))))
  } 

Thanks in advance for your help.

**Comment by dutangc** [comment]
Dear user, 
Could you give us a replicable example ? 
CD
