### ISSUE TITLE
Goodness-of-fit plots performance

### ISSUE THREAD

**Issue by abiadak** [aursiber/fitdistrplus#15]
This is a suggestion more than an issue. When fitting functions to a high number of observations (some thousands) and sending the Goodness-of-fit plots to a pdf or postscript output, the visualisation of those documents is quite slow because of the high number of dots in those documents (and the time it takes to the viewers to render them). Maybe it could be possible, instead of plotting all the observations, to plot a reduced subsample, selecting the points to plot just randomly or by some other smarter method.

**Comment by mldelignette** [comment]
It is possible to use the argument keepdata of fitdist() to limit the number of data points kept for the following, including the GOF plots.
