### ISSUE TITLE
Incomplete cdf ggplot for censored data

### ISSUE THREAD

**Issue by milena-marchant** [aursiber/fitdistrplus#16]
Hello,

I have been trying the package with the provided censored data and I noticed an issue with the CDF plot when requesting the ggplot output. Here is my code:
``` r
library(fitdistrplus)
data("salinity")
fln <- fitdistcens(salinity, "lnorm")
cdfcompcens(fln, plotstyle = "ggplot")
```
This creates the following plot:
![fitdistrplus_cdf](https://user-images.githubusercontent.com/39085218/210760484-b52b20d2-0998-41a8-9098-f3c1fc5eaba1.png)
The empirical cdf is only partially drawn. It seems the vertical lines are from the `geom_rect` layer and the data fields for the `geom_segment` layers only contain seven lines each.

I have not encountered this issue with the `smokedfish` and `fluazinam` data sets.
I tested the code above with R 4.1.3 and R 4.2.2 , in both cases with the most recent version of `{fitdistrplus}` (1.1-8).

Is there something I'm missing to make this plot work?

Thank you for your attention

**Comment by aursiber** [comment]
Thanks for the report!
Fixed in e2f9d48e01a533f46e99d6ff894161a20e90446b
