### ISSUE TITLE
`CI.lty` option no applied in CIcdfplot (ggplot plotstyle)

### ISSUE THREAD

**Issue by milena-marchant** [aursiber/fitdistrplus#17]
Hello again,

Thank you very much for your quick answer last time.
I noticed something else while using the ggplot outputs of the package. The `CI.lty` argument in the `CIcdfplot` function does not seem to have any effect.  I looked a bit at the function code and it seems that it was just left out of the geom_line() calls when constructing the intervals, so it should be an easy fix 🙂 

``` r
library(fitdistrplus)
library(ggplot2)

set.seed(123)
s1 <- rexp(50, 1)
f1 <- fitdist(s1, "exp")
b1 <- bootdist(f1, niter= 11) #voluntarily low to decrease computation time
# Create CIcdfplot with solid CI limit lines
CIcdfplot(b1, CI.output = "probability", CI.fill = "#d3d3d3", CI.lty = 1, plotstyle = "ggplot")
```
![image](https://user-images.githubusercontent.com/39085218/212300510-8dcf09f9-1d0b-4f2b-a034-bbb7ef7ff5b9.png)

**Comment by aursiber** [comment]
Thanks for the report!
Fixed in 3a70f6ae83b3c4b06bd3c0d17eaaf514c8be8a9a
