### ISSUE TITLE
ggplot2 conflict

### ISSUE THREAD

**Issue by Indril22h** [aursiber/fitdistrplus#19]
I received the following warning:

Warning message:
The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.
ℹ The deprecated feature was likely used in the fitdistrplus package.
  Please report the issue at <https://github.com/aursiber/fitdistrplus/issues>.

**Comment by aursiber** [comment]
Thanks for the report.
Solved in adfd1f8bc2acb805625c9267c04431ef26eb46bb
