### ISSUE TITLE
Cullen-Frey plot in ggplot2?

### ISSUE THREAD

**Issue by acfrery** [aursiber/fitdistrplus#2]
Hello,

Thanks for this impressive package! Have you considered using ggplot2? It would be great to have the "descdist" function in this dialect, in order to be able to easily add points, and to change the theme.

Thanks for your attention,

Alejandro

**Comment by royfrancis** [comment]
Actually, I would prefer an option to return the data used to generate the Cullen & Frey graph. So I can plot more than one observation/dataset on the same plot. 

**Update**: Created a new topic (#11) as this is slightly deviating from this request.

**Comment by PaulStott** [comment]
You could use par(mfrow=c(2,2)) followed by descdist() to get multiple C&F plots side-by-side/one on top of the other.

**Comment by dutangc** [comment]
Thanks for the idea. Added to our todolist.
