### ISSUE TITLE
Inconvenience in plotdistcens

### ISSUE THREAD

**Issue by rpouillot** [aursiber/fitdistrplus#20]
Hi, 
Thanks for the package. I run in an error that took me some time to solve: If "right" is before "left" in the data.frame, it leads to an error.
Here is the simplest reproducible example. 
`data(smokedfish)`
`plotdistcens(data.frame(right=smokedfish$right, left=smokedfish$left))`

Thank you.

**Comment by aursiber** [comment]
Thanks for the report.
Solved in 394818e494bff7062d6415db81927658e775fa77.
