### ISSUE TITLE
Normal distribution - Estimated SD not equal to observed SD

### ISSUE THREAD

**Issue by emily-scorgie** [aursiber/fitdistrplus#22]
Code below. In the case of normal distribution, I would expect MME SD = MLE SD = data SD, but this is not the case. In the example below the data SD is different to the other two. Is this a mistake?

x<-c(0.48,3.43,0.23,5,1.2,0.44,1.63,0.31,2.78,4,1.29,3.33,0.96)
x2<-log10(x)

model_mme<-fitdist(x2, "norm", method="mme")
model_mle<-fitdist(x2, "norm", method="mle")

model_mme
model_mle

mean(x2)
sd(x2)

**Comment by dutangc** [comment]
sd() use an unbiased estimator of sigma. If you compute the biased estimator, you get back the MLE 
```
> sd(x2) * sqrt( (length(x2)-1)/length(x2) )
[1] 0.4317305
```
