### ISSUE TITLE
Cullen-Frey graph: Lognormal only works for huge samples

### ISSUE THREAD

**Issue by thmild** [aursiber/fitdistrplus#23]
Dear authors,

your nice Cullen-Frey graph has a curve shown for the lognormal distribution. However, even for large samples (100 000), the point calculated from the sample is usually much closer to the Gamma line than the lognormal curve, which is also true for the bootstrap replications. It does work nicely for huge samples (10 000 000). 

Perhaps users should be cautioned about this?

Best
Thoralf

**Comment by dutangc** [comment]
Thanks Thoralf, we should add this point to the FAQ and to the man. 
The true answer is to this issue will be to use trimmed linear skewness and kurtosis which always exist (even for distribution with infinite mean). This will be down for future release.

**Comment by dutangc** [comment]
Issue added to the FAQ.
