### ISSUE TITLE
Suggestion: move "observation" legend at top of theoretical distribution legend

### ISSUE THREAD

**Issue by gmgeorg** [aursiber/fitdistrplus#24]
I have a suggestion for the "Cullen and Frey graph" to be a bit less confusing: the legend on the right should include also the "[blue dot] observations" marker ( on top of or below all the theoretical distribution).

Right now, at first glance it appears that the observations are falling at the top left corner of the graph with a skewness^2 of 1 and a kurtosis of ~1.2.  It took me multiple checks to realize that that is the  legend, not the actual data point in the (kurtosis, skew^2) plane. This is further exasperated if data follows closely to a normal distribution as then the actual blue dot kind of disappears behind the Normal dot/star shaped pattern - and the only blue dot on graph is the legend ( but it's not clear at all it's a legend)

See e.g.  https://stats.stackexchange.com/a/629866/11476

I ll attach an example adaptation of the plot that I think would be more clear to read / interpret.

**Comment by gmgeorg** [comment]
See here for an example of before/after, with some other nit improvements for visual clarity/increase data-ink ratio.

Before
![b70c7e50-8aa2-4ad3-a00f-64a4353b7adb](https://github.com/aursiber/fitdistrplus/assets/48655643/a4922e1c-4afe-410f-99ea-cdef46f26f45)

After
![73ffaaf1-dbc7-47b9-87ea-56e123580d10](https://github.com/aursiber/fitdistrplus/assets/48655643/ea7ac0e9-5d5e-4b49-86b6-eb7bb3c1b7b8)
and w/ `boot = 100` for a heavy-tailed Lambert W x Normal distribution using 

```
library(LambertW)
set.seed(10)
x <- rLambertW(n=1000, "normal", theta=list(beta=c(mu = 1, sigma=2), 
                                            delta=0.15))
```
![4f1c6c9a-fb8c-4abb-81ad-db62424cf782](https://github.com/aursiber/fitdistrplus/assets/48655643/ba2b5a6f-9c69-45c5-b636-3ac6698746c4)

**Comment by aursiber** [comment]
Thanks for the suggestion.
The legend is now improved (see d6eeb4c1e6064e60fdc7a1cd8dada18cacc6a9b1 and f5a892b5e2c34fdcbf50666363134680144c9860).
