### ISSUE TITLE
Quantile matching to quantile-probabiity pairs

### ISSUE THREAD

**Issue by dmi3kno** [aursiber/fitdistrplus#26]
Could `qmedist()` treat the vector of values $x$ as the vector of quantiles corresponding to the  `probs`, for cases where `length(x)==length(probs)`?

**Comment by mldelignette** [comment]
The purpose of fitdistrplus is exclusively to fit distributions on data. You can look at the SHELF package   (https://cran.r-project.org/web/packages/SHELF/index.html) to fit distributions from quantiles (e.g. for elicitation).
