### ISSUE TITLE
descdist: row 135 and 142 lines(s2,y,lty=2) and lines(s2,y,lty=3) takes forever

### ISSUE THREAD

**Issue by mablmabl** [aursiber/fitdistrplus#30]
I refer to line numbers in descdist.R here at GitHub.
If I remove the lty=2 or lty=3 from the code everything works fine.
It seems that calculation of lty takes extremely long time. This is surprising since lines() is in a system library.
If I run the example with groundbeef data from vignette descdist have not finalized after one hour when lty is present as in the current version. If I create a new function descdist2 without lty it takes less than a second to run - i.e. instant.
I have RStudio 2023.12.1.402, R 4.3.2, Windows 11 23H2, fitdistrplus 1.1-11 from cran.

One possible workaround that works for me:
    lines(s2[s2<=par("usr")[2]+1],y[s2<=par("usr")[2]+1],lty=2)
    lines(s2[s2<=par("usr")[2]+1],y[s2<=par("usr")[2]+1],lty=3)

**Comment by aursiber** [comment]
Thanks a lot for your report.
The `lines` issue in `descdist` was solved in 2d4f24734d7525c48c4244b70df247a685a03615
