### ISSUE TITLE
Shape and rate parameters for gamma distribution changed with the latest update

### ISSUE THREAD

**Issue by WendyMartin1** [aursiber/fitdistrplus#31]
Previously with a dataset, and default MLE with Nelder-Mead, was getting shape and rate parameters of 1782.207 and 1385.945. 

Now that the update is live, I get 1761.800 and 1370.498.

Dataset attached.

Can you help?

Also, I can no longer set the optimization method to optim.method = "L-BFGS-B". I get the following error:

Error in fitdist(data, distr = "gamma", optim.method = "L-BFGS-B") : 
  the function mle failed to estimate the parameters, 
                with the error code 100[
[Furnace2.txt](https://github.com/user-attachments/files/16321866/Furnace2.txt)
](url)

**Comment by dutangc** [comment]
Dear Wendy, we are currently investigating your issue. This is probably due to a wrong initial value for the gamma distribution. Before the formal answer, you can use the mmedist()$estimate as the initial value for fitdist(). CD

**Comment by matt439miller** [comment]
Getting a whole series of issues which are giving me error code 100[

**Comment by dutangc** [comment]
Dear users, 
Indeed, the issue was due to a wrong initial value of the rate parameter for the gamma distribution (previously computed as a scale parameter). There is a new version on github which fix this issue. 
Regards, CD
