### ISSUE TITLE
mgedist with Anderson-Darling fails on large heavy-tailed samples

### ISSUE THREAD

**Issue by Eiim** [aursiber/fitdistrplus#34]
When samples have distributions have heavier tails than expected, AD fits tend to fail, assuming enough of the tail is in the sample. Weibull distribution fits seem to be easier to observe this failure mode in, and in some distributions (like exponential) I could not replicate it except with very extreme samples (eg. from Cauchy). Additionally, K-S and Cramer von Mises statistics are able to fit the data fine.

Tested in R 4.4.1 with `fitdistrplus` 1.2-1.
```r
library(fitdistrplus)
set.seed(12345)
testWeib <- rweibull(100000, 2, 2) + rweibull(100000, 3, 1) + rweibull(100000, 1, 3) # Heavier-tailed than single Weibull, but not extremely so
mgedist(sample(testWeib, 1000), "weibull", gof="AD") # Succeeds
mgedist(sample(testWeib, 5000), "weibull", gof="AD") # Fails
mgedist(testWeib, "weibull", gof="KS") # Succeeds with full data
mgedist(testWeib, "weibull", gof="CvM") # Succeeds with full data

set.seed(12345)
testNorm <- rnorm(100000) + rt(100000, df=3) # Definitely heavier-tailed than normal
mgedist(sample(testNorm, 1000), "norm", gof="AD") # Succeeds
mgedist(sample(testNorm, 5000), "norm", gof="AD") # Fails
mgedist(testNorm, "norm", gof="KS") # Succeeds with full data
mgedist(testNorm, "norm", gof="CvM") # Succeeds with full data
```

Alternate versions with explicitly given data:
```r
mgedist(c(rep(1, 13), 10), "weibull", gof="AD") # Succeeds
mgedist(c(rep(1, 14), 10), "weibull", gof="AD") # Fails
mgedist(c(1:20, 1066), "weibull", gof="AD") # Succeeds
mgedist(c(1:20, 1067), "weibull", gof="AD") # Fails
```

**Comment by dutangc** [comment]
Thanks for reporting this issue. GoF distance use the logarithm of the probabilities (from cdf) and so sometimes, a logarithm of zero occurs which cause an infinite value of the metric. We will investigate.

**Comment by dutangc** [comment]
Dear Ethan, a new devel version of the package is available on github which takes care of numerical issues and applies a scaling of the objective function. Could you test this new version? please do

```
remotes::install_github("lbbe-software/fitdistrplus")
```

**Comment by Eiim** [comment]
Very nice, this appears to be fixed! Thank you!

**Comment by dutangc** [comment]
Perfect. In fact, we previously relied on the numerical accuracy of log(1-p) when p is close to 1. That's why an infinite appear when the sample is very skewed.
