### ISSUE TITLE
Fitting raises warning that NaNs are produced

### ISSUE THREAD

**Issue by frederikziebell** [aursiber/fitdistrplus#5]
It happens very often that I get 'NaNs produced' warnings after a fit, although the fit is fine:

```
set.seed(1)
x <- rlnorm(10^4)
fit <- fitdist(x,"lnorm")
qqcomp(fit,plotstyle="ggplot") +
  scale_x_log10() +
  scale_y_log10()
```
Is there a way that you could turn off the warnings internally? It seems not to be related to the quality of the fit so the user should not have to worry about it.

**Comment by aursiber** [comment]
Hi, 
Your code works with us. We are unable to reproduce your error. 
Have you correctly loaded the ggplot2 library? 
Can you please send us the result of the sessionInfo() command?

![Rplot](https://user-images.githubusercontent.com/13218953/97975747-dd198000-1dc9-11eb-8c61-749ffccb602e.png)
